config/routes.rb
Rails.application.routes.draw do
  resources :peralatans
  resources :lensas
  resources :cameras
  resources :merk_cameras
  resources :payments
  resources :invoices
  resources :banks
  resources :clients
  resources :aksesoris
  resources :merk_lensas
  resources :type_cameras
  get 'site/sistemdansyarat'

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :products
  resources :availability_products
  resources :brand_products
  resources :category_products
  get "/:page" => "site#sistemdansyarat" 
  root 'site#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accessorie.rb
class Accessorie < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    belongs_to :aksesori
    belongs_to :category_product
    belongs_to :availability_product

    mount_uploader :image1, ImageUploader
    mount_uploader :image2, ImageUploader
    mount_uploader :image3, ImageUploader
    mount_uploader :image4, ImageUploader
    mount_uploader :image5, ImageUploader
end

app/models/aksesori.rb
class Aksesori < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    has_many :peralatans
end

app/models/bank.rb
class Bank < ApplicationRecord
end

app/models/brand_product.rb
class BrandProduct < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    has_many :products
end

app/models/camera.rb
class Camera < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    belongs_to :merk_camera
    belongs_to :category_product
    belongs_to :type_camera
    belongs_to :availability_product

    mount_uploader :image1, ImageUploader
    mount_uploader :image2, ImageUploader
    mount_uploader :image3, ImageUploader
    mount_uploader :image4, ImageUploader
    mount_uploader :image5, ImageUploader
end

app/models/client.rb
class Client < ApplicationRecord
    def self.get_id
        # seems broken in high connection because no lock lol seems unlikely to happen for this site tho
        # could be broken because race condition 
        self.maximum(:id) ? self.maximum(:id) + 1 : 1
    end

    def self.generate_id_client
        'C'+self.get_id.to_s.rjust(6,'0')
    end

    extend FriendlyId
    friendly_id :name, use: :slugged
    
    mount_uploader :upload_ktp, ImageUploader
    mount_uploader :upload_kk, ImageUploader
    mount_uploader :upload_identitas, ImageUploader

    belongs_to :products
    has_many :invoices
end

app/models/invoice.rb
class Invoice < ApplicationRecord
    belongs_to :client
    belongs_to :product
end

app/models/lensa.rb
class Lensa < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    belongs_to :merk_lensa
    belongs_to :category_product
    belongs_to :availability_product

    mount_uploader :image1, ImageUploader
    mount_uploader :image2, ImageUploader
    mount_uploader :image3, ImageUploader
    mount_uploader :image4, ImageUploader
    mount_uploader :image5, ImageUploader
end

app/models/merk_camera.rb
class MerkCamera < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    has_many :cameras
end

app/models/merk_lensa.rb
class MerkLensa < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    has_many :lensas
end

app/models/payment.rb
class Payment < ApplicationRecord
    belongs_to :invoice
    belongs_to :bank
    belongs_to :client
end

app/models/peralatan.rb
class Peralatan < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    belongs_to :aksesori
    belongs_to :category_product
    belongs_to :availability_product

    mount_uploader :image1, ImageUploader
    mount_uploader :image2, ImageUploader
    mount_uploader :image3, ImageUploader
    mount_uploader :image4, ImageUploader
    mount_uploader :image5, ImageUploader
end

app/models/product.rb
class Product < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    mount_uploader :image1, ImageUploader
    mount_uploader :image2, ImageUploader
    mount_uploader :image3, ImageUploader
    mount_uploader :image4, ImageUploader
    mount_uploader :image5, ImageUploader
    mount_uploader :image6, ImageUploader
    mount_uploader :image7, ImageUploader
    mount_uploader :image8, ImageUploader
    mount_uploader :image9, ImageUploader
    mount_uploader :image10, ImageUploader

    belongs_to :category_product
    belongs_to :brand_product
    belongs_to :availability_product
    belongs_to :type_camera
    belongs_to :merk_lensa
    belongs_to :aksesori
    belongs_to :client

    has_many :invoices
end

app/models/type_camera.rb
class TypeCamera < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    has_many :cameras
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/peralatans_controller.rb
class PeralatansController < ApplicationController
  before_action :set_peralatan, only: [:show, :edit, :update, :destroy]

  # GET /peralatans
  # GET /peralatans.json
  def index
    @peralatans = Peralatan.all
  end

  # GET /peralatans/1
  # GET /peralatans/1.json
  def show
    @peralatan = Peralatan.friendly.find(params[:id])
  end

  # GET /peralatans/new
  def new
    @peralatan = Peralatan.new
  end

  # GET /peralatans/1/edit
  def edit
  end

  # POST /peralatans
  # POST /peralatans.json
  def create
    @peralatan = Peralatan.new(peralatan_params)

    respond_to do |format|
      if @peralatan.save
        format.html { redirect_to @peralatan, notice: 'Peralatan was successfully created.' }
        format.json { render :show, status: :created, location: @peralatan }
      else
        format.html { render :new }
        format.json { render json: @peralatan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /peralatans/1
  # PATCH/PUT /peralatans/1.json
  def update
    respond_to do |format|
      if @peralatan.update(peralatan_params)
        format.html { redirect_to @peralatan, notice: 'Peralatan was successfully updated.' }
        format.json { render :show, status: :ok, location: @peralatan }
      else
        format.html { render :edit }
        format.json { render json: @peralatan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /peralatans/1
  # DELETE /peralatans/1.json
  def destroy
    @peralatan.destroy
    respond_to do |format|
      format.html { redirect_to peralatans_url, notice: 'Peralatan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_peralatan
      @peralatan = Peralatan.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def peralatan_params
      params.require(:peralatan).permit(:category_product_id, :availability_product_id, :aksesori_id, :name, :slug, :peralatan_description, :peralatan_kelengkapan, :price, :review_video, :image1, :image2, :image3, :image4, :image5)
    end
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/cameras_helper.rb
module CamerasHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/lensas_helper.rb
module LensasHelper
end

app/helpers/peralatans_helper.rb
module PeralatansHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/peralatans/_form.html.erb
<%= form_with(model: peralatan, local: true) do |form| %>
  <% if peralatan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(peralatan.errors.count, "error") %> prohibited this peralatan from being saved:</h2>

      <ul>
      <% peralatan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category_product_id %>
    <%= form.number_field :category_product_id, id: :peralatan_category_product_id %>
  </div>

  <div class="field">
    <%= form.label :availability_product_id %>
    <%= form.number_field :availability_product_id, id: :peralatan_availability_product_id %>
  </div>

  <div class="field">
    <%= form.label :aksesori_id %>
    <%= form.number_field :aksesori_id, id: :peralatan_aksesori_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :peralatan_name %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug, id: :peralatan_slug %>
  </div>

  <div class="field">
    <%= form.label :peralatan_description %>
    <%= form.text_area :peralatan_description, id: :peralatan_peralatan_description %>
  </div>

  <div class="field">
    <%= form.label :peralatan_kelengkapan %>
    <%= form.text_area :peralatan_kelengkapan, id: :peralatan_peralatan_kelengkapan %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :peralatan_price %>
  </div>

  <div class="field">
    <%= form.label :review_video %>
    <%= form.text_field :review_video, id: :peralatan_review_video %>
  </div>

  <div class="field">
    <%= form.label :image1 %>
    <%= form.text_field :image1, id: :peralatan_image1 %>
  </div>

  <div class="field">
    <%= form.label :image2 %>
    <%= form.text_field :image2, id: :peralatan_image2 %>
  </div>

  <div class="field">
    <%= form.label :image3 %>
    <%= form.text_field :image3, id: :peralatan_image3 %>
  </div>

  <div class="field">
    <%= form.label :image4 %>
    <%= form.text_field :image4, id: :peralatan_image4 %>
  </div>

  <div class="field">
    <%= form.label :image5 %>
    <%= form.text_field :image5, id: :peralatan_image5 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/peralatans/edit.html.erb
<h1>Editing Peralatan</h1>

<%= render 'form', peralatan: @peralatan %>

<%= link_to 'Show', @peralatan %> |
<%= link_to 'Back', peralatans_path %>

app/views/peralatans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Peralatans</h1>

<table>
  <thead>
    <tr>
      <th>Category product</th>
      <th>Availability product</th>
      <th>Aksesori</th>
      <th>Name</th>
      <th>Slug</th>
      <th>Peralatan description</th>
      <th>Peralatan kelengkapan</th>
      <th>Price</th>
      <th>Review video</th>
      <th>Image1</th>
      <th>Image2</th>
      <th>Image3</th>
      <th>Image4</th>
      <th>Image5</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @peralatans.each do |peralatan| %>
      <tr>
        <td><%= peralatan.category_product_id %></td>
        <td><%= peralatan.availability_product_id %></td>
        <td><%= peralatan.aksesori_id %></td>
        <td><%= peralatan.name %></td>
        <td><%= peralatan.slug %></td>
        <td><%= peralatan.peralatan_description %></td>
        <td><%= peralatan.peralatan_kelengkapan %></td>
        <td><%= peralatan.price %></td>
        <td><%= peralatan.review_video %></td>
        <td><%= peralatan.image1 %></td>
        <td><%= peralatan.image2 %></td>
        <td><%= peralatan.image3 %></td>
        <td><%= peralatan.image4 %></td>
        <td><%= peralatan.image5 %></td>
        <td><%= link_to 'Show', peralatan %></td>
        <td><%= link_to 'Edit', edit_peralatan_path(peralatan) %></td>
        <td><%= link_to 'Destroy', peralatan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Peralatan', new_peralatan_path %>

app/views/peralatans/new.html.erb
<h1>New Peralatan</h1>

<%= render 'form', peralatan: @peralatan %>

<%= link_to 'Back', peralatans_path %>

app/views/peralatans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category product:</strong>
  <%= @peralatan.category_product_id %>
</p>

<p>
  <strong>Availability product:</strong>
  <%= @peralatan.availability_product_id %>
</p>

<p>
  <strong>Aksesori:</strong>
  <%= @peralatan.aksesori_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @peralatan.name %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @peralatan.slug %>
</p>

<p>
  <strong>Peralatan description:</strong>
  <%= @peralatan.peralatan_description %>
</p>

<p>
  <strong>Peralatan kelengkapan:</strong>
  <%= @peralatan.peralatan_kelengkapan %>
</p>

<p>
  <strong>Price:</strong>
  <%= @peralatan.price %>
</p>

<p>
  <strong>Review video:</strong>
  <%= @peralatan.review_video %>
</p>

<p>
  <strong>Image1:</strong>
  <%= @peralatan.image1 %>
</p>

<p>
  <strong>Image2:</strong>
  <%= @peralatan.image2 %>
</p>

<p>
  <strong>Image3:</strong>
  <%= @peralatan.image3 %>
</p>

<p>
  <strong>Image4:</strong>
  <%= @peralatan.image4 %>
</p>

<p>
  <strong>Image5:</strong>
  <%= @peralatan.image5 %>
</p>

<%= link_to 'Edit', edit_peralatan_path(@peralatan) %> |
<%= link_to 'Back', peralatans_path %>