config/routes.rb
Rails.application.routes.draw do
  resources :peralatans
  resources :lensas
  resources :cameras
  resources :merk_cameras
  resources :payments
  resources :invoices
  resources :banks
  resources :clients
  resources :aksesoris
  resources :merk_lensas
  resources :type_cameras
  get 'site/sistemdansyarat'

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :products
  resources :availability_products
  resources :brand_products
  resources :category_products
  get "/:page" => "site#sistemdansyarat" 
  root 'site#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accessorie.rb
class Accessorie < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    belongs_to :aksesori
    belongs_to :category_product
    belongs_to :availability_product

    mount_uploader :image1, ImageUploader
    mount_uploader :image2, ImageUploader
    mount_uploader :image3, ImageUploader
    mount_uploader :image4, ImageUploader
    mount_uploader :image5, ImageUploader
end

app/models/aksesori.rb
class Aksesori < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    has_many :peralatans
end

app/models/bank.rb
class Bank < ApplicationRecord
end

app/models/brand_product.rb
class BrandProduct < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    has_many :products
end

app/models/camera.rb
class Camera < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    belongs_to :merk_camera
    belongs_to :category_product
    belongs_to :type_camera
    belongs_to :availability_product

    mount_uploader :image1, ImageUploader
    mount_uploader :image2, ImageUploader
    mount_uploader :image3, ImageUploader
    mount_uploader :image4, ImageUploader
    mount_uploader :image5, ImageUploader
end

app/models/client.rb
class Client < ApplicationRecord
    def self.get_id
        # seems broken in high connection because no lock lol seems unlikely to happen for this site tho
        # could be broken because race condition 
        self.maximum(:id) ? self.maximum(:id) + 1 : 1
    end

    def self.generate_id_client
        'C'+self.get_id.to_s.rjust(6,'0')
    end

    extend FriendlyId
    friendly_id :name, use: :slugged
    
    mount_uploader :upload_ktp, ImageUploader
    mount_uploader :upload_kk, ImageUploader
    mount_uploader :upload_identitas, ImageUploader

    belongs_to :products
    has_many :invoices
end

app/models/invoice.rb
class Invoice < ApplicationRecord
    belongs_to :client
    belongs_to :product
end

app/models/lensa.rb
class Lensa < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    belongs_to :merk_lensa
    belongs_to :category_product
    belongs_to :availability_product

    mount_uploader :image1, ImageUploader
    mount_uploader :image2, ImageUploader
    mount_uploader :image3, ImageUploader
    mount_uploader :image4, ImageUploader
    mount_uploader :image5, ImageUploader
end

app/models/merk_camera.rb
class MerkCamera < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    has_many :cameras
end

app/models/merk_lensa.rb
class MerkLensa < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    has_many :lensas
end

app/models/payment.rb
class Payment < ApplicationRecord
    belongs_to :invoice
    belongs_to :bank
    belongs_to :client
end

app/models/peralatan.rb
class Peralatan < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    belongs_to :aksesori
    belongs_to :category_product
    belongs_to :availability_product

    mount_uploader :image1, ImageUploader
    mount_uploader :image2, ImageUploader
    mount_uploader :image3, ImageUploader
    mount_uploader :image4, ImageUploader
    mount_uploader :image5, ImageUploader
end

app/models/product.rb
class Product < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    mount_uploader :image1, ImageUploader
    mount_uploader :image2, ImageUploader
    mount_uploader :image3, ImageUploader
    mount_uploader :image4, ImageUploader
    mount_uploader :image5, ImageUploader
    mount_uploader :image6, ImageUploader
    mount_uploader :image7, ImageUploader
    mount_uploader :image8, ImageUploader
    mount_uploader :image9, ImageUploader
    mount_uploader :image10, ImageUploader

    belongs_to :category_product
    belongs_to :brand_product
    belongs_to :availability_product
    belongs_to :type_camera
    belongs_to :merk_lensa
    belongs_to :aksesori
    belongs_to :client

    has_many :invoices
end

app/models/type_camera.rb
class TypeCamera < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    has_many :cameras
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/merk_cameras_controller.rb
class MerkCamerasController < ApplicationController
  before_action :set_merk_camera, only: [:show, :edit, :update, :destroy]

  # GET /merk_cameras
  # GET /merk_cameras.json
  def index
    @merk_cameras = MerkCamera.all
  end

  # GET /merk_cameras/1
  # GET /merk_cameras/1.json
  def show
    @merk_camera = MerkCamera.friendly.find(params[:id])
  end

  # GET /merk_cameras/new
  def new
    @merk_camera = MerkCamera.new
  end

  # GET /merk_cameras/1/edit
  def edit
  end

  # POST /merk_cameras
  # POST /merk_cameras.json
  def create
    @merk_camera = MerkCamera.new(merk_camera_params)

    respond_to do |format|
      if @merk_camera.save
        format.html { redirect_to @merk_camera, notice: 'Merk camera was successfully created.' }
        format.json { render :show, status: :created, location: @merk_camera }
      else
        format.html { render :new }
        format.json { render json: @merk_camera.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /merk_cameras/1
  # PATCH/PUT /merk_cameras/1.json
  def update
    respond_to do |format|
      if @merk_camera.update(merk_camera_params)
        format.html { redirect_to @merk_camera, notice: 'Merk camera was successfully updated.' }
        format.json { render :show, status: :ok, location: @merk_camera }
      else
        format.html { render :edit }
        format.json { render json: @merk_camera.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /merk_cameras/1
  # DELETE /merk_cameras/1.json
  def destroy
    @merk_camera.destroy
    respond_to do |format|
      format.html { redirect_to merk_cameras_url, notice: 'Merk camera was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merk_camera
      @merk_camera = MerkCamera.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def merk_camera_params
      params.require(:merk_camera).permit(:name, :slug)
    end
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/cameras_helper.rb
module CamerasHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/lensas_helper.rb
module LensasHelper
end

app/helpers/merk_cameras_helper.rb
module MerkCamerasHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/merk_cameras/_form.html.erb
<%= form_with(model: merk_camera, local: true) do |form| %>
  <% if merk_camera.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(merk_camera.errors.count, "error") %> prohibited this merk_camera from being saved:</h2>

      <ul>
      <% merk_camera.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :merk_camera_name %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug, id: :merk_camera_slug %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/merk_cameras/edit.html.erb
<h1>Editing Merk Camera</h1>

<%= render 'form', merk_camera: @merk_camera %>

<%= link_to 'Show', @merk_camera %> |
<%= link_to 'Back', merk_cameras_path %>

app/views/merk_cameras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Merk Cameras</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @merk_cameras.each do |merk_camera| %>
      <tr>
        <td><%= merk_camera.name %></td>
        <td><%= merk_camera.slug %></td>
        <td><%= link_to 'Show', merk_camera %></td>
        <td><%= link_to 'Edit', edit_merk_camera_path(merk_camera) %></td>
        <td><%= link_to 'Destroy', merk_camera, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Merk Camera', new_merk_camera_path %>

app/views/merk_cameras/new.html.erb
<h1>New Merk Camera</h1>

<%= render 'form', merk_camera: @merk_camera %>

<%= link_to 'Back', merk_cameras_path %>

app/views/merk_cameras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @merk_camera.name %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @merk_camera.slug %>
</p>

<%= link_to 'Edit', edit_merk_camera_path(@merk_camera) %> |
<%= link_to 'Back', merk_cameras_path %>