config/routes.rb
Rails.application.routes.draw do
  resources :peralatans
  resources :lensas
  resources :cameras
  resources :merk_cameras
  resources :payments
  resources :invoices
  resources :banks
  resources :clients
  resources :aksesoris
  resources :merk_lensas
  resources :type_cameras
  get 'site/sistemdansyarat'

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :products
  resources :availability_products
  resources :brand_products
  resources :category_products
  get "/:page" => "site#sistemdansyarat" 
  root 'site#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accessorie.rb
class Accessorie < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    belongs_to :aksesori
    belongs_to :category_product
    belongs_to :availability_product

    mount_uploader :image1, ImageUploader
    mount_uploader :image2, ImageUploader
    mount_uploader :image3, ImageUploader
    mount_uploader :image4, ImageUploader
    mount_uploader :image5, ImageUploader
end

app/models/aksesori.rb
class Aksesori < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    has_many :peralatans
end

app/models/bank.rb
class Bank < ApplicationRecord
end

app/models/brand_product.rb
class BrandProduct < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    has_many :products
end

app/models/camera.rb
class Camera < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    belongs_to :merk_camera
    belongs_to :category_product
    belongs_to :type_camera
    belongs_to :availability_product

    mount_uploader :image1, ImageUploader
    mount_uploader :image2, ImageUploader
    mount_uploader :image3, ImageUploader
    mount_uploader :image4, ImageUploader
    mount_uploader :image5, ImageUploader
end

app/models/client.rb
class Client < ApplicationRecord
    def self.get_id
        # seems broken in high connection because no lock lol seems unlikely to happen for this site tho
        # could be broken because race condition 
        self.maximum(:id) ? self.maximum(:id) + 1 : 1
    end

    def self.generate_id_client
        'C'+self.get_id.to_s.rjust(6,'0')
    end

    extend FriendlyId
    friendly_id :name, use: :slugged
    
    mount_uploader :upload_ktp, ImageUploader
    mount_uploader :upload_kk, ImageUploader
    mount_uploader :upload_identitas, ImageUploader

    belongs_to :products
    has_many :invoices
end

app/models/invoice.rb
class Invoice < ApplicationRecord
    belongs_to :client
    belongs_to :product
end

app/models/lensa.rb
class Lensa < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    belongs_to :merk_lensa
    belongs_to :category_product
    belongs_to :availability_product

    mount_uploader :image1, ImageUploader
    mount_uploader :image2, ImageUploader
    mount_uploader :image3, ImageUploader
    mount_uploader :image4, ImageUploader
    mount_uploader :image5, ImageUploader
end

app/models/merk_camera.rb
class MerkCamera < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    has_many :cameras
end

app/models/merk_lensa.rb
class MerkLensa < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    has_many :lensas
end

app/models/payment.rb
class Payment < ApplicationRecord
    belongs_to :invoice
    belongs_to :bank
    belongs_to :client
end

app/models/peralatan.rb
class Peralatan < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    belongs_to :aksesori
    belongs_to :category_product
    belongs_to :availability_product

    mount_uploader :image1, ImageUploader
    mount_uploader :image2, ImageUploader
    mount_uploader :image3, ImageUploader
    mount_uploader :image4, ImageUploader
    mount_uploader :image5, ImageUploader
end

app/models/product.rb
class Product < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    mount_uploader :image1, ImageUploader
    mount_uploader :image2, ImageUploader
    mount_uploader :image3, ImageUploader
    mount_uploader :image4, ImageUploader
    mount_uploader :image5, ImageUploader
    mount_uploader :image6, ImageUploader
    mount_uploader :image7, ImageUploader
    mount_uploader :image8, ImageUploader
    mount_uploader :image9, ImageUploader
    mount_uploader :image10, ImageUploader

    belongs_to :category_product
    belongs_to :brand_product
    belongs_to :availability_product
    belongs_to :type_camera
    belongs_to :merk_lensa
    belongs_to :aksesori
    belongs_to :client

    has_many :invoices
end

app/models/type_camera.rb
class TypeCamera < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    has_many :cameras
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
 

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.friendly.find(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:category_product_id, :brand_product_id, :availability_product_id, :name, :description, :kelengkapan, :price, :review_video, :image1, :image2, :image3, :image4, :image5, :image6, :image7, :image8, :image9, :image10)
    end
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/cameras_helper.rb
module CamerasHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/lensas_helper.rb
module LensasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category_product_id %>
    <%= form.number_field :category_product_id, id: :product_category_product_id %>
  </div>

  <div class="field">
    <%= form.label :brand_product_id %>
    <%= form.number_field :brand_product_id, id: :product_brand_product_id %>
  </div>

  <div class="field">
    <%= form.label :availability_product %>
    <%= form.number_field :availability_product, id: :product_availability_product %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 5, cols: 25, :class => "tinymce", id: :product_description %>
  </div>

  <div class="field">
    <%= form.label :kelengkapan %>
    <%= form.text_area :kelengkapan, rows: 5, cols: 25, :class => "tinymce", id: :product_kelengkapan %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :product_price %>
  </div>

  <div class="field">
    <%= form.label :review_video %>
    <%= form.text_field :review_video, id: :product_review_video %>
  </div>

  <div class="field">
    <%= form.label :image1 %>
    <%= form.file_field :image1, id: :product_image1, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :image2 %>
    <%= form.file_field :image2, id: :product_image2, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :image3 %>
    <%= form.file_field :image3, id: :product_image3, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :image4 %>
    <%= form.file_field :image4, id: :product_image4, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :image5 %>
    <%= form.file_field :image5, id: :product_image5, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :image6 %>
    <%= form.file_field :image6, id: :product_image6, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :image7 %>
    <%= form.file_field :image7, id: :product_image7, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :image8 %>
    <%= form.file_field :image8, id: :product_image8, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :image9 %>
    <%= form.file_field :image9, id: :product_image9, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :image10 %>
    <%= form.file_field :image10, id: :product_image10, :class => "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>
<%= tinymce %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Category product</th>
      <th>Brand product</th>
      <th>Availability product</th>
      <th>Name</th>
      <th>Description</th>
      <th>Kelengkapan</th>
      <th>Price</th>
      <th>Review video</th>
      <th>Image1</th>
      <th>Image2</th>
      <th>Image3</th>
      <th>Image4</th>
      <th>Image5</th>
      <th>Image6</th>
      <th>Image7</th>
      <th>Image8</th>
      <th>Image9</th>
      <th>Image10</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.category_product_id %></td>
        <td><%= product.brand_product_id %></td>
        <td><%= product.availability_product_id %></td>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.kelengkapan %></td>
        <td><%= product.price %></td>
        <td><%= product.review_video %></td>
        <td><%= product.image1 %></td>
        <td><%= product.image2 %></td>
        <td><%= product.image3 %></td>
        <td><%= product.image4 %></td>
        <td><%= product.image5 %></td>
        <td><%= product.image6 %></td>
        <td><%= product.image7 %></td>
        <td><%= product.image8 %></td>
        <td><%= product.image9 %></td>
        <td><%= product.image10 %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<%= render 'site/navbar-all' %>
<div class="container card-detail-prod m-t-100 m-b-100">
		<div class="card">
			<div class="container-fliud">
				<div class="wrapper row">
					<div class="preview col-md-6">
						<div class="preview-pic tab-content">
              <div class="tab-pane active" id="pic-1">
                <div class="img-magnifier-container">
                  <%= image_tag @product.image1, alt: 'product image 1', class: 'img-fluid', id: 'myimage' %>
                </div>
              </div>
						  <div class="tab-pane" id="pic-2">
                <div class="img-magnifier-container">
                  <%= image_tag @product.image2, alt: 'product image 2', class: 'img-fluid', id: 'myimage' %>
                </div>
              </div>
						  <div class="tab-pane" id="pic-3">
                <div class="img-magnifier-container">
                  <%= image_tag @product.image3, alt: 'product image 3', class: 'img-fluid', id: 'myimage' %>
                </div>
              </div>
						</div>
						<ul class="preview-thumbnail nav nav-tabs">
						  <li class="active"><a data-target="#pic-1" data-toggle="tab"><%= image_tag @product.image1, alt: 'product image 1', class: 'img-fluid' %></a></li>
						  <li><a data-target="#pic-2" data-toggle="tab"><%= image_tag @product.image2, alt: 'product image 2', class: 'img-fluid' %></a></li>
						  <li><a data-target="#pic-3" data-toggle="tab"><%= image_tag @product.image3, alt: 'product image 3', class: 'img-fluid' %></a></li>
						</ul>
					</div>
					<div class="details col-md-6">
						<h3 class="product-title"><%= @product.name %></h3>
						<%= @product.description.html_safe %>
            <br>
            <%= @product.kelengkapan.html_safe %>
            <br>
						<h5 class="price">Current price: <span>Rp <%= @product.price %></span></h5>
            <h5 class="price">Availability: <span> <%= @product.availability_product.name %></span></h5>
            <p><strong>Have question?</strong></p>
            <ul class="list-unstyled nav">
              <li class="m-r-10">
              <a target="_blank" rel="noopener noreferrer" href="https://www.instagram.com/pakehero/">
              <span><%= image_tag 'instagram.png', alt: 'instagram', class: 'img-fluid' %></span>
              </a>
              </li>
              <li class="m-r-10">
                <a target="_blank" rel="noopener noreferrer" href="https://api.whatsapp.com/send?phone=6281222225939">
                  <span><%= image_tag 'whatsapp.png', alt: 'whatsapp', class: 'img-fluid' %></span>
                </a>
              </li>
            </ul>
            <div>
              <!-- <%= link_to 'Sewa kamera', new_client_path(product_id: @product.id), class: "btn btn-grab-it float-right"%> -->
              <%= link_to 'Sewa kamera', new_client_path, class: "btn btn-grab-it float-right"%>
            </div>
					</div>
				</div>
			</div>
		</div>
	</div>

  <%= render 'site/contact'%>

  <script>
(function ($) {
    "use strict"; // Start of use strict

    // Smooth scrolling using jQuery easing
    $('a.js-scroll-trigger[href*="#"]:not([href="#"])').click(function () {
        if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') && location.hostname == this.hostname) {
            var target = $(this.hash);
            target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
            if (target.length) {
                $('html, body').animate({
                    scrollTop: (target.offset().top - 56)
                }, 1000, "easeInOutExpo");
                return false;
            }
        }
    });

    // Closes responsive menu when a scroll trigger link is clicked
    $('.js-scroll-trigger').click(function () {
        $('.navbar-collapse').collapse('hide');
    });

    // Activate scrollspy to add active class to navbar items on scroll
    $('body').scrollspy({
        target: '#mainNavall',
        offset: 57
    });

    // Collapse Navbar
    var navbarCollapse = function () {
        var mainNavall = $('#mainNavall');
        if (mainNavall.length) {
            if ($("#mainNavall").offset().top > 100) {
                $("#mainNavall").addClass("navbar-shrink");
            } else {
                $("#mainNavall").removeClass("navbar-shrink");
            }
        }
    };
    // Collapse now if page is not at top
    navbarCollapse();
    // Collapse the navbar when page is scrolled
    $(window).scroll(navbarCollapse);

    // Scroll reveal calls
    window.sr = ScrollReveal();

    sr.reveal('.sr-icon-1', {
        delay: 200,
        scale: 0
    });
    sr.reveal('.sr-icon-2', {
        delay: 400,
        scale: 0
    });
    sr.reveal('.sr-icon-3', {
        delay: 600,
        scale: 0
    });
    sr.reveal('.sr-icon-4', {
        delay: 800,
        scale: 0
    });
    sr.reveal('.sr-button', {
        delay: 200,
        distance: '15px',
        origin: 'bottom',
        scale: 0.8
    });
    sr.reveal('.sr-contact-1', {
        delay: 200,
        scale: 0
    });
    sr.reveal('.sr-contact-2', {
        delay: 400,
        scale: 0
    });

    // Magnific popup calls
    $('.popup-gallery').magnificPopup({
        delegate: 'a',
        type: 'image',
        tLoading: 'Loading image #%curr%...',
        mainClass: 'mfp-img-mobile',
        gallery: {
            enabled: true,
            navigateByImgClick: true,
            preload: [0, 1]
        },
        image: {
            tError: '<a href="%url%">The image #%curr%</a> could not be loaded.'
        }
    });

})(jQuery); // End of use strict

</script>

<!-- <p id="notice"><%= notice %></p>

<p>
  <strong>Category product:</strong>
  <%= @product.category_product_id %>
</p>

<p>
  <strong>Brand product:</strong>
  <%= @product.brand_product_id %>
</p>

<p>
  <strong>Availability product:</strong>
  <%= @product.availability_product_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Kelengkapan:</strong>
  <%= @product.kelengkapan %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Review video:</strong>
  <%= @product.review_video %>
</p>
<%= link_to 'Sewa kamera', new_client_path(product_id: @product.id), class: "btn btn-grab-it float-right"%>
<p>
  <strong>Image1:</strong>
  <div class="img-magnifier-container">
    <%= image_tag @product.image1, alt: 'product image 1', class: 'img-fluid', id: 'myimage' %>
  </div>
</p>

<p>
  <strong>Image2:</strong>
  <%= @product.image2 %><%= link_to 'Sewa kamera', new_client_path(product_id: @product.id), class: "btn btn-grab-it float-right"%>
</p>

<p>
  <strong>Image3:</strong>
  <%= @product.image3 %>
</p>

<p>
  <strong>Image4:</strong>
  <%= @product.image4 %>
</p>

<p>
  <strong>Image5:</strong>
  <%= @product.image5 %>
</p>

<p>
  <strong>Image6:</strong>
  <%= @product.image6 %>
</p>

<p>
  <strong>Image7:</strong>
  <%= @product.image7 %>
</p>

<p>
  <strong>Image8:</strong><%= link_to 'Sewa kamera', new_client_path(product_id: @product.id), class: "btn btn-grab-it float-right"%>
  <%= @product.image8 %>
</p>

<p>
  <strong>Image9:</strong>
  <%= @product.image9 %>
</p>

<p>
  <strong>Image10:</strong>
  <%= @product.image10 %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
--> 