config/routes.rb
Rails.application.routes.draw do
  resources :peralatans
  resources :lensas
  resources :cameras
  resources :merk_cameras
  resources :payments
  resources :invoices
  resources :banks
  resources :clients
  resources :aksesoris
  resources :merk_lensas
  resources :type_cameras
  get 'site/sistemdansyarat'

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :products
  resources :availability_products
  resources :brand_products
  resources :category_products
  get "/:page" => "site#sistemdansyarat" 
  root 'site#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accessorie.rb
class Accessorie < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    belongs_to :aksesori
    belongs_to :category_product
    belongs_to :availability_product

    mount_uploader :image1, ImageUploader
    mount_uploader :image2, ImageUploader
    mount_uploader :image3, ImageUploader
    mount_uploader :image4, ImageUploader
    mount_uploader :image5, ImageUploader
end

app/models/aksesori.rb
class Aksesori < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    has_many :peralatans
end

app/models/bank.rb
class Bank < ApplicationRecord
end

app/models/brand_product.rb
class BrandProduct < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    has_many :products
end

app/models/camera.rb
class Camera < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    belongs_to :merk_camera
    belongs_to :category_product
    belongs_to :type_camera
    belongs_to :availability_product

    mount_uploader :image1, ImageUploader
    mount_uploader :image2, ImageUploader
    mount_uploader :image3, ImageUploader
    mount_uploader :image4, ImageUploader
    mount_uploader :image5, ImageUploader
end

app/models/category_product.rb
class CategoryProduct < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    has_many :cameras
    has_many :lensas
    has_many :peralatans
end

app/models/client.rb
class Client < ApplicationRecord
    def self.get_id
        # seems broken in high connection because no lock lol seems unlikely to happen for this site tho
        # could be broken because race condition 
        self.maximum(:id) ? self.maximum(:id) + 1 : 1
    end

    def self.generate_id_client
        'C'+self.get_id.to_s.rjust(6,'0')
    end

    extend FriendlyId
    friendly_id :name, use: :slugged
    
    mount_uploader :upload_ktp, ImageUploader
    mount_uploader :upload_kk, ImageUploader
    mount_uploader :upload_identitas, ImageUploader

    belongs_to :products
    has_many :invoices
end

app/models/invoice.rb
class Invoice < ApplicationRecord
    belongs_to :client
    belongs_to :product
end

app/models/lensa.rb
class Lensa < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    belongs_to :merk_lensa
    belongs_to :category_product
    belongs_to :availability_product

    mount_uploader :image1, ImageUploader
    mount_uploader :image2, ImageUploader
    mount_uploader :image3, ImageUploader
    mount_uploader :image4, ImageUploader
    mount_uploader :image5, ImageUploader
end

app/models/merk_camera.rb
class MerkCamera < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    has_many :cameras
end

app/models/merk_lensa.rb
class MerkLensa < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    has_many :lensas
end

app/models/payment.rb
class Payment < ApplicationRecord
    belongs_to :invoice
    belongs_to :bank
    belongs_to :client
end

app/models/peralatan.rb
class Peralatan < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    belongs_to :aksesori
    belongs_to :category_product
    belongs_to :availability_product

    mount_uploader :image1, ImageUploader
    mount_uploader :image2, ImageUploader
    mount_uploader :image3, ImageUploader
    mount_uploader :image4, ImageUploader
    mount_uploader :image5, ImageUploader
end

app/models/product.rb
class Product < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    mount_uploader :image1, ImageUploader
    mount_uploader :image2, ImageUploader
    mount_uploader :image3, ImageUploader
    mount_uploader :image4, ImageUploader
    mount_uploader :image5, ImageUploader
    mount_uploader :image6, ImageUploader
    mount_uploader :image7, ImageUploader
    mount_uploader :image8, ImageUploader
    mount_uploader :image9, ImageUploader
    mount_uploader :image10, ImageUploader

    belongs_to :category_product
    belongs_to :brand_product
    belongs_to :availability_product
    belongs_to :type_camera
    belongs_to :merk_lensa
    belongs_to :aksesori
    belongs_to :client

    has_many :invoices
end

app/models/type_camera.rb
class TypeCamera < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged

    has_many :cameras
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/category_products_controller.rb
class CategoryProductsController < ApplicationController
  before_action :set_category_product, only: [:show, :edit, :update, :destroy]

  # GET /category_products
  # GET /category_products.json
  def index
    @category_products = CategoryProduct.all
  end

  # GET /category_products/1
  # GET /category_products/1.json
  def show
    @cameras = @category_product.cameras.all.paginate(:page => params[:page], :per_page => 9)
    @lensas = @category_product.lensas.all.paginate(:page => params[:page], :per_page => 9)
    @peralatans = @category_product.peralatans.all.paginate(:page => params[:page], :per_page => 9)
    if params[:type_camera_id]
      @cameras = @category_product.cameras.where(type_camera_id: params[:type_camera_id]).order("created_at ASC").paginate(:page => params[:page], :per_page => 9)
    elsif params[:merk_lensa_id]
      @lensas = @category_product.lensas.where(merk_lensa_id: params[:merk_lensa_id]).order("created_at ASC").paginate(:page => params[:page], :per_page => 9)
    elsif params[:aksesori_id]
      @accessories = @category_product.accessories.where(aksesori_id: params[:aksesori_id]).order("created_at ASC").paginate(:page => params[:page], :per_page => 9)
    end
  end

  # GET /category_products/new
  def new
    @category_product = CategoryProduct.new
  end

  # GET /category_products/1/edit
  def edit
  end

  # POST /category_products
  # POST /category_products.json
  def create
    @category_product = CategoryProduct.new(category_product_params)

    respond_to do |format|
      if @category_product.save
        format.html { redirect_to @category_product, notice: 'Category product was successfully created.' }
        format.json { render :show, status: :created, location: @category_product }
      else
        format.html { render :new }
        format.json { render json: @category_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /category_products/1
  # PATCH/PUT /category_products/1.json
  def update
    respond_to do |format|
      if @category_product.update(category_product_params)
        format.html { redirect_to @category_product, notice: 'Category product was successfully updated.' }
        format.json { render :show, status: :ok, location: @category_product }
      else
        format.html { render :edit }
        format.json { render json: @category_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /category_products/1
  # DELETE /category_products/1.json
  def destroy
    @category_product.destroy
    respond_to do |format|
      format.html { redirect_to category_products_url, notice: 'Category product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category_product
      @category_product = CategoryProduct.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_product_params
      params.require(:category_product).permit(:name)
    end
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/cameras_helper.rb
module CamerasHelper
end

app/helpers/category_products_helper.rb
module CategoryProductsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/lensas_helper.rb
module LensasHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/category_products/_form.html.erb
<%= form_with(model: category_product, local: true) do |form| %>
  <% if category_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category_product.errors.count, "error") %> prohibited this category_product from being saved:</h2>

      <ul>
      <% category_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_product_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/category_products/_navbar-all.html.erb
<!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top navbar-custom" id="mainNav-all">
      <div class="container">
        <%= link_to "#{image_tag('logo-pakehero.jpg', style: 'width: 30px; height:30px; border-radius:50%; margin-right:5px;', class: 'd-inline-block align-top')} Pake Hero".html_safe, root_path, class: 'navbar-brand link-back-to-home' %>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to 'Home', root_path, class: 'nav-link link-back-to-home' %>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Syarat Order</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sistem Order</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Our Product
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <% CategoryProduct.all.each do |category_product| %>
                  <%= link_to category_product.name, category_product, class: 'dropdown-item' %>
                <% end %>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
            </li>
          </ul>
        </div>
      </div>
</nav>

app/views/category_products/edit.html.erb
<h1>Editing Category Product</h1>

<%= render 'form', category_product: @category_product %>

<%= link_to 'Show', @category_product %> |
<%= link_to 'Back', category_products_path %>

app/views/category_products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Category Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @category_products.each do |category_product| %>
      <tr>
        <td><%= category_product.name %></td>
        <td><%= link_to 'Show', category_product %></td>
        <td><%= link_to 'Edit', edit_category_product_path(category_product) %></td>
        <td><%= link_to 'Destroy', category_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category Product', new_category_product_path %>

app/views/category_products/new.html.erb
<h1>New Category Product</h1>

<%= render 'form', category_product: @category_product %>

<%= link_to 'Back', category_products_path %>

app/views/category_products/show.html.erb
<%= render 'site/navbar-all' %>
<!-- Page Content -->
    <div class="container">

      <div class="row m-t-70 m-b-70">

        <div class="col-lg-3 catprod">

          <h3 class="my-4"><%= @category_product.name %></h3>
          <div class="list-group">
            <% if @category_product.id == 1 %>
                <% TypeCamera.all.each do |type_camera| %>
                    <%= link_to type_camera.name, category_product_path(:type_camera_id => type_camera.id), class: 'list-group-item', method: :get %>
                <% end %>
            <% elsif @category_product.id == 2 %>
                <% MerkLensa.all.each do |merk_lensa| %>
                    <%= link_to merk_lensa.name, category_product_path(:merk_lensa_id => merk_lensa.id), class: 'list-group-item', method: :get %>
                <% end %>
            <% else %>
                <% Aksesori.all.each do |aksesori| %>
                    <%= link_to aksesori.name, category_product_path(:aksesori_id => aksesori.id), class: 'list-group-item', method: :get %>
                <% end %>
            <% end %>
          </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">
          <div class="row m-t-80 m-b-80">
          <% if @category_product.id == 1 %>
            <% @cameras.each do |camera| %>
              <div class="col-lg-4 col-md-6 mb-4 card-product">
                <div class="card shadow mb-5 bg-white rounded ">
                  <%= link_to image_tag(camera.image1, alt: camera.name, class: 'card-img-top'), camera_path(camera), class: "p-l-20 p-r-20 p-b-20 p-t-20" %>
                  <div class="card-body">
                    <h5 class="card-title">
                      <%= link_to camera.name, camera_path(camera) %>
                    </h5>
                    <h6>Rp. <%= camera.price %>,-</h6>
                    <%= link_to 'Lihat detail', camera_path(camera), class: "btn btn-grab-it"%>
                  </div>
                  <div class="card-footer">
                    <small class="text-muted"><%= camera.availability_product.name %></small>
                  </div>
                </div>
              </div>
            <% end %>
            <%= will_paginate @cameras, list_classes: %w(pagination justify-content-center), renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

        <% elsif @category_product.id == 2 %>
            <% @lensas.each do |lensa| %>
              <div class="col-lg-4 col-md-6 mb-4 card-product">
                <div class="card shadow mb-5 bg-white rounded ">
                  <%= link_to image_tag(lensa.image1, alt: lensa.name, class: 'card-img-top'), lensa_path(lensa), class: "p-l-20 p-r-20 p-b-20 p-t-20" %>
                  <div class="card-body">
                    <h5 class="card-title">
                      <%= link_to lensa.name, lensa_path(lensa) %>
                    </h5>
                    <h6>Rp. <%= lensa.price %>,-</h6>
                    <%= link_to 'Lihat detail', lensa_path(lensa), class: "btn btn-grab-it"%>
                  </div>
                  <div class="card-footer">
                    <small class="text-muted"><%= lensa.availability_product.name %></small>
                  </div>
                </div>
              </div>
            <% end %>
            <%= will_paginate @lensas, list_classes: %w(pagination justify-content-center), renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

        <% elsif @category_product.id == 3 %>
            <% @peralatans.each do |peralatan| %>
              <div class="col-lg-4 col-md-6 mb-4 card-product">
                <div class="card shadow mb-5 bg-white rounded ">
                  <%= link_to image_tag(peralatan.image1, alt: peralatan.name, class: 'card-img-top'), peralatan_path(peralatan), class: "p-l-20 p-r-20 p-b-20 p-t-20" %>
                  <div class="card-body">
                    <h5 class="card-title">
                      <%= link_to peralatan.name, peralatan_path(peralatan) %>
                    </h5>
                    <h6>Rp. <%= peralatan.price %>,-</h6>
                    <%= link_to 'Lihat detail', peralatan_path(peralatan), class: "btn btn-grab-it"%>
                  </div>
                  <div class="card-footer">
                    <small class="text-muted"><%= peralatan.availability_product.name %></small>
                  </div>
                </div>
              </div>
            <% end %>

            <%= will_paginate @peralatans, list_classes: %w(pagination justify-content-center), renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
        <% end %>
        
          </div>
          <!-- /.row -->
        </div>
        <!-- /.col-lg-9 -->

      </div>
      <!-- /.row -->
            
        </div>
        <!-- /.col-lg-9 -->

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->
<%= render 'site/contact'%>

<script>
(function ($) {
    "use strict"; // Start of use strict

    // Smooth scrolling using jQuery easing
    $('a.js-scroll-trigger[href*="#"]:not([href="#"])').click(function () {
        if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') && location.hostname == this.hostname) {
            var target = $(this.hash);
            target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
            if (target.length) {
                $('html, body').animate({
                    scrollTop: (target.offset().top - 56)
                }, 1000, "easeInOutExpo");
                return false;
            }
        }
    });

    // Closes responsive menu when a scroll trigger link is clicked
    $('.js-scroll-trigger').click(function () {
        $('.navbar-collapse').collapse('hide');
    });

    // Activate scrollspy to add active class to navbar items on scroll
    $('body').scrollspy({
        target: '#mainNavall',
        offset: 57
    });

    // Collapse Navbar
    var navbarCollapse = function () {
        var mainNavall = $('#mainNavall');
        if (mainNavall.length) {
            if ($("#mainNavall").offset().top > 100) {
                $("#mainNavall").addClass("navbar-shrink");
            } else {
                $("#mainNavall").removeClass("navbar-shrink");
            }
        }
    };
    // Collapse now if page is not at top
    navbarCollapse();
    // Collapse the navbar when page is scrolled
    $(window).scroll(navbarCollapse);

    // Scroll reveal calls
    window.sr = ScrollReveal();

    sr.reveal('.sr-icon-1', {
        delay: 200,
        scale: 0
    });
    sr.reveal('.sr-icon-2', {
        delay: 400,
        scale: 0
    });
    sr.reveal('.sr-icon-3', {
        delay: 600,
        scale: 0
    });
    sr.reveal('.sr-icon-4', {
        delay: 800,
        scale: 0
    });
    sr.reveal('.sr-button', {
        delay: 200,
        distance: '15px',
        origin: 'bottom',
        scale: 0.8
    });
    sr.reveal('.sr-contact-1', {
        delay: 200,
        scale: 0
    });
    sr.reveal('.sr-contact-2', {
        delay: 400,
        scale: 0
    });

    // Magnific popup calls
    $('.popup-gallery').magnificPopup({
        delegate: 'a',
        type: 'image',
        tLoading: 'Loading image #%curr%...',
        mainClass: 'mfp-img-mobile',
        gallery: {
            enabled: true,
            navigateByImgClick: true,
            preload: [0, 1]
        },
        image: {
            tError: '<a href="%url%">The image #%curr%</a> could not be loaded.'
        }
    });

})(jQuery); // End of use strict

</script>

<script>
$(document).ready(function(){
  $('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    autoplay:true,
    items: 2,
    nav: true,
    autoplayTimeout:3000,
    autoplayHoverPause:true,
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
            nav:true
        },
        600:{
            items:2,
            nav:false
        },
        1000:{
            items:3,
            nav:true
        }
    }
})
});
</script>


<!-- <p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category_product.name %>
</p>

<%= link_to 'Edit', edit_category_product_path(@category_product) %> |
<%= link_to 'Back', category_products_path %> -->